name: Build and deploy ASP.Net Core app to Azure Web App - az-asprazor-app

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - name: Build with dotnet
        run: dotnet build ./az-asprazor-app/az-asprazor-app.sln --configuration Release

      - name: dotnet publish
        run: dotnet publish ./az-asprazor-app/az-asprazor-app.sln -c Release -o ${{github.workspace}}/myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: .net-app
          path: ${{github.workspace}}/myapp

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: .net-app
          path: ${{github.workspace}}/myapp

      - name: List downloaded files
        run: dir ${{github.workspace}}/myapp
      
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'az-asprazor-app'
          slot-name: 'Production'
          package: ${{github.workspace}}/myapp
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_789FD9D05ADE40C29CC81C373F2457C2 }}
